#ifndef CPP1_KRUL_HTTPSTATUSCODE_HPP
#define CPP1_KRUL_HTTPSTATUSCODE_HPP

enum HttpStatusCode
{
        // 100 range
        CONTINUE = 100,
        SWITCHING_PROTOCOLS = 101,

        // 200 range
        OK = 200,
        CREATED = 201,
        ACCEPTED = 202,
        NON_AUTHORITIVE_INFORMATION = 203,
        NO_CONTENT = 204,
        RESET_CONTENT = 205,
        PARTIAL_CONTENT = 206,

        // 300 range
        MULTIPLE_CHOICES = 300,
        MOVED = 301,
        REDIRECT = 302,
        SEE_OTHER = 303,
        NOT_MODIFIED = 304,
        USE_PROXY = 305,
        UN_USED = 306,
        TEMPORARY_REDIRECT = 307,

        // 400 range
        BAD_REQUEST = 400,
        UNAUTHORIZED = 401,
        PAYMENT_REQUIRED = 402,
        FORBIDDEN = 403,
        NOT_FOUND = 404,
        METHOD_NOT_ALLOWED = 405,
        NOT_ACCEPTABLE = 406,
        PROXY_AUTHENTICATION_REQUIRED = 407,
        REQUEST_TIMEOUT = 408,
        CONFLICT = 409,
        GONE = 410,
        LENGTH_REQUIRED = 411,
        PRECONDITION_FAILED = 412,
        REQUEST_ENTITY_TOO_LARGE = 413,
        REQUEST_URI_TOO_LONG = 414,
        UNSUPPORTED_MEDIA_TYPE = 415,
        REQUESTED_RANGE_NOT_SATISFIABLE = 416,
        EXPECTATION_FAILED = 417,
        UPGRADE_REQUIRED = 426,

        // 500 range
        INTERNAL_SERVER_ERROR = 500,
        NOT_IMPLEMENTED = 501,
        BAD_GATEWAY = 502,
        SERVICE_UNAVAILABLE = 503,
        GATEWAY_TIMEOUT = 504,
        HTTP_VERSION_NOT_SUPPORTED = 505,
};

#endif //CPP1_KRUL_HTTPSTATUSCODE_HPP
